image: node:16.14.0

stages:
  - prepare
  - release
  - publish
  - deploy-storybook

##################
### Actions NOT on tag
##################

tag_version:
  stage: prepare
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - npm run prerelease_version
    - git commit -am 'Bumping version to $(npm run show_version --silent)'
    - git tag -a "$(npm run show_version --silent)" -m "CI Tagging version $(npm run show_version --silent)"
    - git push --tags https://root:$GITLAB_API_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
  tags:
    - build-xl
  except:
    - tags

pages:
  stage: deploy-storybook
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  script:
    - npm i
    - npm run build-storybook
  tags:
    - build-xl
  only:
    - main
    - develop
  except:
    - tags

release_patch:
  stage: release
  script:
    - echo "$npm_package_version test patch"
    # bump version then publish lib
  tags:
    - build-xl
  only:
    - main
  when: manual

release_version:
  stage: release
  script:
    - echo "$npm_package_version test version"
    # bump version then publish lib
  tags:
    - build-xl
  only:
    - main
  when: manual

##################
### Actions on tag
##################

publish:
  stage: publish
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm run build sb-legendre-lib
  script:
    - npm config set @liksi:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - npm run publish_lib
  after_script:
    - echo $(npm run show_version --silent)
  tags:
    - build-xl
  only:
    - tags