image: node:16.14.0

stages:
  - publish
  - deploy-storybook

publish:
  stage: publish
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm run build sb-legendre-lib
  script:
    - npm config set @liksi:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - npm run publish_lib
  tags:
    - build-xl
  only:
    - tags

pages:
  stage: deploy-storybook
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  script:
    - npm i
    - npm run build-storybook
  tags:
    - build-xl
  except:
    - tags
